### ISSUE TITLE
Init handler for a component inside Singleton executes for every component

### ISSUE THREAD

**Issue by CaptainDX** [pozil/lightning-singleton#1]
Readme says that c:someComponent will only be loaded once and its init handler will only be triggered once but init is triggered every time because the init handler is executed before c:Singleton rendering.

The only solution I found is making isActive public and doing something like this:

`<c:Singleton name="mySingleton" isActive="{!v.isActive}">
    <aura:if isTrue="{!v.isActive}">
       <c:someComponent />
    </aura:if>
</c:Singleton>`

But any other solution would be appreciated :)

**Comment by pozil** [comment]
Hi @CaptainDX, I could have sworn that it was working at some point in time but I confirm that it's not working in its current state. As you discovered, the `init` function is always called in child components even if they are not rendered.

I was able to fix that issue by dynamically spawning the singleton's child component.
Update your project with the new version and check the updated readme for the new configuration.
